### ISSUE TITLE
Convert to lua

### ISSUE THREAD

**Issue by rofrol** [Mokronos/config#1]
I have found your comment in https://github.com/mokronos/.dotfiles/blob/e101800d9ef5b46211222369c4e5e053cb03ceb9/nvim/.config/nvim/after/ftplugin/text.lua#L3

You can look at my config https://github.com/rofrol/LazyVim--starter/blob/bab2c8d5360520f2ae11863981b909d74dcda041/lua/plugins/spell.lua

**Comment by mokronos** [comment]
@rofrol I'm a little late, but thanks :)
